import type { Metadata } from "next";
import { LegalPage } from "../legal-page";

export const metadata: Metadata = {
  title: "Terms of Service — ACT Prep",
  description: "The terms governing use of the ACT Prep service.",
};

// ⚠️ REVIEW REQUIRED: This is a working draft to satisfy Stripe's published-Terms
// requirement and give users a real agreement. Have a lawyer review before
// relying on it — especially the company name/contact, governing law, liability,
// and refund sections marked [BRACKETS].
export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="July 8, 2026">
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the ACT Prep
        website and application (the &ldquo;Service&rdquo;), operated by{" "}
        <strong>[COMPANY LEGAL NAME]</strong> (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or
        &ldquo;our&rdquo;). By creating an account or using the Service, you agree to these Terms.
        If you do not agree, do not use the Service.
      </p>

      <h2>1. Who may use the Service</h2>
      <p>
        The Service is intended for students preparing for the ACT and for the parents or guardians
        who support them. If you are under 18, you may use the Service only with the involvement and
        consent of a parent or legal guardian, who agrees to these Terms on your behalf. A parent or
        guardian who creates or funds an account is responsible for that account and for supervising
        the student&rsquo;s use.
      </p>

      <h2>2. Accounts</h2>
      <p>
        You must provide accurate information when you register and keep your login credentials
        secure. You are responsible for all activity under your account. Notify us promptly of any
        unauthorized use.
      </p>

      <h2>3. Subscriptions, billing, and cancellation</h2>
      <p>
        The Service is offered as a paid subscription of <strong>$20 per month</strong>, billed
        through our payment processor, Stripe. New subscriptions may begin with a{" "}
        <strong>7-day free trial</strong>; unless you cancel before the trial ends, your payment
        method will be charged the subscription fee and then on a recurring monthly basis until you
        cancel.
      </p>
      <p>
        A single subscription may cover a linked student and parent account as described in the
        Service. You can cancel at any time through the billing portal; cancellation takes effect at
        the end of the current billing period, and you retain access until then.{" "}
        <strong>[REFUND POLICY: state whether fees are refundable — e.g., &ldquo;Fees already
        charged are non-refundable except where required by law.&rdquo;]</strong>
      </p>
      <p>
        We may change subscription pricing on reasonable advance notice; changes apply to billing
        periods after the notice.
      </p>

      <h2>4. Practice scores are estimates</h2>
      <p>
        Scores, projected composites, and analytics produced by the Service are{" "}
        <strong>projected estimates generated by a heuristic model</strong> for practice guidance
        only. They are not official ACT scores and do not predict your actual ACT result. ACT&reg;
        is a registered trademark of its owner; we are not affiliated with, endorsed by, or
        sponsored by ACT, Inc.
      </p>

      <h2>5. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>share, resell, or provide access to your account or the content to others;</li>
        <li>copy, scrape, or redistribute the practice questions, passages, or explanations;</li>
        <li>attempt to bypass the paywall, security, or access controls;</li>
        <li>disrupt or misuse the Service or interfere with other users.</li>
      </ul>

      <h2>6. Intellectual property</h2>
      <p>
        All practice content, passages, questions, explanations, and software are owned by us or our
        licensors and are protected by law. We grant you a personal, non-transferable, revocable
        license to use the Service for your own ACT preparation while your subscription is active.
      </p>

      <h2>7. Termination</h2>
      <p>
        You may stop using the Service and cancel at any time. We may suspend or terminate access if
        you violate these Terms or misuse the Service. Sections that by their nature should survive
        termination (e.g., intellectual property, disclaimers, limitation of liability) will
        survive.
      </p>

      <h2>8. Disclaimers</h2>
      <p>
        The Service is provided &ldquo;as is&rdquo; without warranties of any kind, to the fullest
        extent permitted by law. We do not warrant that the Service will be uninterrupted, error-free,
        or that using it will improve your test scores.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        <strong>
          [REVIEW WITH COUNSEL]
        </strong>{" "}
        To the fullest extent permitted by law, our total liability arising out of or relating to the
        Service will not exceed the amount you paid us in the twelve months before the claim, and we
        will not be liable for indirect, incidental, or consequential damages.
      </p>

      <h2>10. Governing law and disputes</h2>
      <p>
        These Terms are governed by the laws of <strong>[STATE/COUNTRY]</strong>, without regard to
        conflict-of-laws rules. <strong>[Specify dispute resolution — courts of a venue, or
        arbitration — with counsel.]</strong>
      </p>

      <h2>11. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. If we make material changes, we will update the
        &ldquo;Last updated&rdquo; date and, where appropriate, notify you. Continued use after
        changes take effect constitutes acceptance.
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions about these Terms? Contact us at <strong>[SUPPORT EMAIL]</strong>.
      </p>
    </LegalPage>
  );
}
